/*
Nudm_EE

Nudm Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package udmclient

import (
	"encoding/json"
	"time"
)

// ReportingOptions struct for ReportingOptions
type ReportingOptions struct {
	ReportMode *EventReportMode `json:"reportMode,omitempty"`
	MaxNumOfReports *int32 `json:"maxNumOfReports,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	Expiry *time.Time `json:"expiry,omitempty"`
	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  
	SamplingRatio *int32 `json:"samplingRatio,omitempty"`
	// indicating a time in seconds.
	GuardTime *int32 `json:"guardTime,omitempty"`
	// indicating a time in seconds.
	ReportPeriod *int32 `json:"reportPeriod,omitempty"`
	NotifFlag *NotificationFlag `json:"notifFlag,omitempty"`
}

// NewReportingOptions instantiates a new ReportingOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportingOptions() *ReportingOptions {
	this := ReportingOptions{}
	return &this
}

// NewReportingOptionsWithDefaults instantiates a new ReportingOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportingOptionsWithDefaults() *ReportingOptions {
	this := ReportingOptions{}
	return &this
}

// GetReportMode returns the ReportMode field value if set, zero value otherwise.
func (o *ReportingOptions) GetReportMode() EventReportMode {
	if o == nil || o.ReportMode == nil {
		var ret EventReportMode
		return ret
	}
	return *o.ReportMode
}

// GetReportModeOk returns a tuple with the ReportMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportingOptions) GetReportModeOk() (*EventReportMode, bool) {
	if o == nil || o.ReportMode == nil {
		return nil, false
	}
	return o.ReportMode, true
}

// HasReportMode returns a boolean if a field has been set.
func (o *ReportingOptions) HasReportMode() bool {
	if o != nil && o.ReportMode != nil {
		return true
	}

	return false
}

// SetReportMode gets a reference to the given EventReportMode and assigns it to the ReportMode field.
func (o *ReportingOptions) SetReportMode(v EventReportMode) {
	o.ReportMode = &v
}

// GetMaxNumOfReports returns the MaxNumOfReports field value if set, zero value otherwise.
func (o *ReportingOptions) GetMaxNumOfReports() int32 {
	if o == nil || o.MaxNumOfReports == nil {
		var ret int32
		return ret
	}
	return *o.MaxNumOfReports
}

// GetMaxNumOfReportsOk returns a tuple with the MaxNumOfReports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportingOptions) GetMaxNumOfReportsOk() (*int32, bool) {
	if o == nil || o.MaxNumOfReports == nil {
		return nil, false
	}
	return o.MaxNumOfReports, true
}

// HasMaxNumOfReports returns a boolean if a field has been set.
func (o *ReportingOptions) HasMaxNumOfReports() bool {
	if o != nil && o.MaxNumOfReports != nil {
		return true
	}

	return false
}

// SetMaxNumOfReports gets a reference to the given int32 and assigns it to the MaxNumOfReports field.
func (o *ReportingOptions) SetMaxNumOfReports(v int32) {
	o.MaxNumOfReports = &v
}

// GetExpiry returns the Expiry field value if set, zero value otherwise.
func (o *ReportingOptions) GetExpiry() time.Time {
	if o == nil || o.Expiry == nil {
		var ret time.Time
		return ret
	}
	return *o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportingOptions) GetExpiryOk() (*time.Time, bool) {
	if o == nil || o.Expiry == nil {
		return nil, false
	}
	return o.Expiry, true
}

// HasExpiry returns a boolean if a field has been set.
func (o *ReportingOptions) HasExpiry() bool {
	if o != nil && o.Expiry != nil {
		return true
	}

	return false
}

// SetExpiry gets a reference to the given time.Time and assigns it to the Expiry field.
func (o *ReportingOptions) SetExpiry(v time.Time) {
	o.Expiry = &v
}

// GetSamplingRatio returns the SamplingRatio field value if set, zero value otherwise.
func (o *ReportingOptions) GetSamplingRatio() int32 {
	if o == nil || o.SamplingRatio == nil {
		var ret int32
		return ret
	}
	return *o.SamplingRatio
}

// GetSamplingRatioOk returns a tuple with the SamplingRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportingOptions) GetSamplingRatioOk() (*int32, bool) {
	if o == nil || o.SamplingRatio == nil {
		return nil, false
	}
	return o.SamplingRatio, true
}

// HasSamplingRatio returns a boolean if a field has been set.
func (o *ReportingOptions) HasSamplingRatio() bool {
	if o != nil && o.SamplingRatio != nil {
		return true
	}

	return false
}

// SetSamplingRatio gets a reference to the given int32 and assigns it to the SamplingRatio field.
func (o *ReportingOptions) SetSamplingRatio(v int32) {
	o.SamplingRatio = &v
}

// GetGuardTime returns the GuardTime field value if set, zero value otherwise.
func (o *ReportingOptions) GetGuardTime() int32 {
	if o == nil || o.GuardTime == nil {
		var ret int32
		return ret
	}
	return *o.GuardTime
}

// GetGuardTimeOk returns a tuple with the GuardTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportingOptions) GetGuardTimeOk() (*int32, bool) {
	if o == nil || o.GuardTime == nil {
		return nil, false
	}
	return o.GuardTime, true
}

// HasGuardTime returns a boolean if a field has been set.
func (o *ReportingOptions) HasGuardTime() bool {
	if o != nil && o.GuardTime != nil {
		return true
	}

	return false
}

// SetGuardTime gets a reference to the given int32 and assigns it to the GuardTime field.
func (o *ReportingOptions) SetGuardTime(v int32) {
	o.GuardTime = &v
}

// GetReportPeriod returns the ReportPeriod field value if set, zero value otherwise.
func (o *ReportingOptions) GetReportPeriod() int32 {
	if o == nil || o.ReportPeriod == nil {
		var ret int32
		return ret
	}
	return *o.ReportPeriod
}

// GetReportPeriodOk returns a tuple with the ReportPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportingOptions) GetReportPeriodOk() (*int32, bool) {
	if o == nil || o.ReportPeriod == nil {
		return nil, false
	}
	return o.ReportPeriod, true
}

// HasReportPeriod returns a boolean if a field has been set.
func (o *ReportingOptions) HasReportPeriod() bool {
	if o != nil && o.ReportPeriod != nil {
		return true
	}

	return false
}

// SetReportPeriod gets a reference to the given int32 and assigns it to the ReportPeriod field.
func (o *ReportingOptions) SetReportPeriod(v int32) {
	o.ReportPeriod = &v
}

// GetNotifFlag returns the NotifFlag field value if set, zero value otherwise.
func (o *ReportingOptions) GetNotifFlag() NotificationFlag {
	if o == nil || o.NotifFlag == nil {
		var ret NotificationFlag
		return ret
	}
	return *o.NotifFlag
}

// GetNotifFlagOk returns a tuple with the NotifFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportingOptions) GetNotifFlagOk() (*NotificationFlag, bool) {
	if o == nil || o.NotifFlag == nil {
		return nil, false
	}
	return o.NotifFlag, true
}

// HasNotifFlag returns a boolean if a field has been set.
func (o *ReportingOptions) HasNotifFlag() bool {
	if o != nil && o.NotifFlag != nil {
		return true
	}

	return false
}

// SetNotifFlag gets a reference to the given NotificationFlag and assigns it to the NotifFlag field.
func (o *ReportingOptions) SetNotifFlag(v NotificationFlag) {
	o.NotifFlag = &v
}

func (o ReportingOptions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ReportMode != nil {
		toSerialize["reportMode"] = o.ReportMode
	}
	if o.MaxNumOfReports != nil {
		toSerialize["maxNumOfReports"] = o.MaxNumOfReports
	}
	if o.Expiry != nil {
		toSerialize["expiry"] = o.Expiry
	}
	if o.SamplingRatio != nil {
		toSerialize["samplingRatio"] = o.SamplingRatio
	}
	if o.GuardTime != nil {
		toSerialize["guardTime"] = o.GuardTime
	}
	if o.ReportPeriod != nil {
		toSerialize["reportPeriod"] = o.ReportPeriod
	}
	if o.NotifFlag != nil {
		toSerialize["notifFlag"] = o.NotifFlag
	}
	return json.Marshal(toSerialize)
}

type NullableReportingOptions struct {
	value *ReportingOptions
	isSet bool
}

func (v NullableReportingOptions) Get() *ReportingOptions {
	return v.value
}

func (v *NullableReportingOptions) Set(val *ReportingOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableReportingOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableReportingOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportingOptions(val *ReportingOptions) *NullableReportingOptions {
	return &NullableReportingOptions{value: val, isSet: true}
}

func (v NullableReportingOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportingOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


